- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day, only updates if caches are older than this.
    autoremove: true

- name: apt install standard utilities and packages
  become: true
  apt:
    state: present
    name:
      # acl installed to help with: "Failed to set permissions on the temporary files
      # Ansible needs to create when becoming an unprivileged user"
      # https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary
      - acl
      - fail2ban
      - htop
      - iftop
      - net-tools
      - unattended-upgrades
      - unzip
