- name: create lobby user
  become: true
  user:
    name: "lobby"
    groups: "lobby,docker"
    create_home: no
    system: yes

- name: deploy systemctl service file to run lobby
  become: true
  template:
    src: lobby.service
    dest: /etc/systemd/system/lobby-2.6.service
    owner: root
    group: "{{ admin_group }}"
    mode: 0644

- name: start lobby if it is not already running
  become: true
  service:
    name: lobby-2.6
    state: started
    enabled: true
