lobby_user: lobby
# Full version includes the build number, eg: 2.6+153432
lobby_full_version: "{{ build_version }}"

# product version is just the major.minor, eg: 2.6
lobby_product_version: "{{ product_version }}"
lobby_name: "lobby_{{ lobby_product_version }}"
lobby_home_folder: "/opt/lobby/{{ lobby_product_version }}"

lobby_ports:
  "default": "8080"
  "2.5": "8080"
  "2.6": "9026"

lobby_http_port: "{{ lobby_ports[lobby_product_version] }}"

lobby_db_host: "localhost"
lobby_db_port: "5432"
lobby_db_name: lobby_db
lobby_db_user: lobby_user
github_api_token: "test"
lobby_artifact: triplea-dropwizard-server.zip
lobby_jar_file: triplea-dropwizard-server.jar
lobby_restart_on_new_deployment: true

# How often to run map indexing. We need to be able to index all maps
# before the next run starts to avoid overlapping runs. The smaller this
# value the more responsive indexing will be to map updates.
# 120 -> 2 hours in between runs -> (if indexing 360 / hour) -> 720 maps to be indexed per run
map_indexing_period_minutes: 120

# Indexing delay is how much of a backoff there is between indexing
# each map. We need to keep this number to be under 1000 tasks per
# hour to avoid rate limiting
# 10 => 6 per minute => 360 per hour.
map_indexing_task_delay_seconds: 10

reverse_proxy_server_name: "localhost"

lobby_public_cert_folder: /etc/nginx/certs
lobby_public_cert_file: "{{ lobby_public_cert_folder }}/cert.crt"
lobby_private_key_file: "{{ lobby_public_cert_folder }}//cert.key"

lobby_dhparam_file: "/etc/nginx/dhparam.pem"

# Whether we should generate self signed SSL certs, suitable
# for a dev environment where we are not using letsencrypt to
# obtain certs.
nginx_generate_self_signed_cert: false
