- name: deploy /etc/hosts file with hostname in it
  become: true
  template:
    src: etc_hosts.j2
    dest: /etc/hosts
    mode: 0755
    owner: root
    group: root

- name: set hostname of system
  become: true
  notify: reboot_system
  hostname: 
    name: "{{ hostname }}"
    use: debian
