- name: install java
  become: true
  apt:
    state: present
    name: "openjdk-11-jdk-headless"

- name: create service user {bot}
  become: true
  user:
    name: "bot"
    groups: "bot"
    create_home: no
    system: yes

- name: create folders
  become: true
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: bot
    group: "{{ admin_group }}"
  with_items:
    - "/home/bot/triplea/savedGames/"
    - "{{ bot_install_folder }}"
    - "{{ bot_maps_folder }}"

- name: deploy scripts
  become: true
  template:
    src: "download-all-maps.sh.j2"
    dest: "{{ bot_install_folder }}/download-all-maps.sh"
    owner: "bot"
    group: "{{ admin_group }}"
    mode: "0755"
    
- name: Download Bot Zip File
  become: true
  register: bot_zip_file_download
  get_url:
    url: "{{ bot_zip.url }}"
    dest: "{{ bot_install_folder }}"
    mode: "0644"
    checksum: "md5:{{ bot_zip.md5 }}"
    owner: "bot"
    group: "{{ admin_group }}"

- name: extract zip file
  become: true
  unarchive:
    remote_src: yes
    src: "{{ bot_install_folder }}/triplea-game-headless.zip"
    dest: "{{ bot_install_folder }}/"
    owner: "bot"
    group: "{{ admin_group }}"
    creates: "{{ bot_install_folder }}/bin/triplea-game-headless.jar"

- name: create triplea-root touch file
  become: true
  file:
    state: touch
    path: "{{ bot_install_folder }}/.triplea-root"
    mode: "0644"
    owner: "bot"
    group: "{{ admin_group }}"

- name: ensure logging folder /var/log/triplea exists
  become: true
  file:
    path: /var/log/triplea
    state: directory
    mode: "0755"
    owner: "bot"
    group:  "{{ admin_group }}"

- name: install systemd service script
  become: true
  template:
    src: bot.service.j2
    dest: /lib/systemd/system/bot@.service
    mode: "644"
    owner: root
    group: "{{ admin_group }}"

- name: allow ports
  become: true
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
  with_items: "{{ bot_instances }}"

- name: enable and ensure bots are started
  become: true
  service:
    name: "bot@{{ item.number }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ bot_instances }}"
