- name: assert vars are set
  assert:
    that:
      - bot_number > 0
      - bot_location_city_name != ""

- name: allow ports
  ufw:
    rule: allow
    port: "40{{ item }}"
    proto: tcp
  with_items: "{{ bot_numbers }}"

- name: create service user to run the app
  user:
    name: "{{ bot_user }}"
    create_home: no
    system: yes

- name: deploy scripts to admin home
  template:
    src: "{{ item }}.j2"
    dest: "{{ admin_home }}/{{ item }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0755"
  with_items:
    - start-all
    - stop-all
    - download-all-maps

- name: create folders
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"
  with_items:
    - "{{ bot_folder }}"
    - "{{ bot_install_home }}"
    - "{{ bot_maps_folder }}"

- name: Download Bot Zip File
  register: bot_zip_file_download
  get_url:
    url: "{{ bot_zip_file_url }}"
    dest: "{{ bot_install_home }}"
    mode: "0644"
    checksum: "md5:e83a688423c2441a5f3a89f2db0b8993"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: extract zip file
  when: bot_zip_file_download.changed
  unarchive:
    remote_src: yes
    src: "{{ bot_install_home }}/triplea-game-headless-2.5.22294.zip"
    dest: "{{ bot_install_home }}/"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: create triplea-root touch file
  file:
    state: touch
    path: "{{ bot_install_home }}/.triplea-root"
    mode: "0644"
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"

- name: ensure logging folder /var/log/triplea exists
  file:
    path: /var/log/triplea
    state: directory
    mode: "0755"
    owner: syslog
    group: adm

- name: deploy rsyslog config files to send log output from syslog to files
  register: bot_rsyslog_conf
  template:
    src: bot-rsyslog.conf
    dest: /etc/rsyslog.d/bot{{ item }}.conf
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ bot_numbers }}"

- name: restart rsyslog to pick up any config changes
  when: bot_rsyslog_conf.changed
  service:
    name: rsyslog
    state: restarted

- name: install systemd service script
  register: bot_service
  template:
    src: bot.service.j2
    dest: /lib/systemd/system/bot@.service
    mode: "644"

- name: reload systemd configurations
  when: bot_service.changed
  systemd:
    daemon_reload: yes

- name: enable and ensure bots are started
  service:
    name: "bot@{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ bot_numbers }}"
