- name: create service group {bot}
  become: true
  group:
    name: "bot"
    state: present

- name: create service user {bot}
  become: true
  user:
    name: "bot"
    groups: "bot,docker"
    uid: "999"
    create_home: no
    system: yes

- name: create folders
  become: true
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: bot
    group: "{{ admin_group }}"
  with_items:
    - "/home/bot/triplea/savedGames/"
    - "{{ bot_maps_folder }}"
    - "/var/log/bot/"

- name: deploy scripts
  become: true
  template:
    src: "download-all-maps.sh.j2"
    dest: "/opt/bot/download-all-maps.sh"
    owner: "bot"
    group: "{{ admin_group }}"
    mode: "0755"

- name: create cronjob to download maps daily
  become: true
  cron:
    name: "bot-download-maps"
    special_time: daily
    job: /opt/bot/download-all-maps.sh > /var/log/bot/map-download.log 2>&1
    user: bot

- name: install systemd service script
  become: true
  template:
    src: bot.service.j2
    dest: /lib/systemd/system/bot@.service
    mode: "644"
    owner: root
    group: "{{ admin_group }}"

- name: allow ports
  become: true
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
  with_items: "{{ bot_instances }}"

- name: enable and ensure bots are started
  become: true
  service:
    name: "bot@{{ item.number }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ bot_instances }}"
