- name: create admin group, allows shared access to triplea items like logs
  become: true
  group:
    name: "{{ admin_group }}"
    state: present

- name: create docker group
  become: true
  group:
    name: docker
    state: present

- name: create admin user accounts
  become: true
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    create_home: yes
    append: yes
    groups: "{{ item.name }},{{ admin_group }},docker"
  with_items: "{{ admin_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deployer sudo permissions file - /etc/sudoers.d/{{ admin }}
  become: true
  template:
    src: sudoer_file.sudo
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: "640"
  with_items: "{{ admin_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: SSH keys - create directory - /home/{{admin}}/.ssh/
  become: true
  file:
    path: "/home/{{ item.name }}/.ssh/"
    state: directory
    mode: "700"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: SSH keys - deploy authorized_keys file -  /home/{{admin}}/.ssh/authorized_keys
  become: true
  template:
    src: authorized_keys.j2
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    mode: "600"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  loop_control:
    label: "{{ item.name }}"
