- name: apt install nginx
  apt:
    name: nginx
    state: present

- name: deploy nginx sites_enabled configuation
  template:
    src: etc_nginx_sites_enabled_default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: "0644"
    owner: root
    group: root

- name: allow ports
  tags: firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "443"
    - "80"

- name: ensure nginx is started
  systemd:
    name: nginx
    state: started
    enabled: true
