- name: make sure incorrect versions of docker are not installed
  become: true
  package:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

# Install instructions at: https://docs.docker.com/engine/install/ubuntu/

- name: ensure keyring directory exists
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root

- name: stat docker keyring file so we can check if it exists
  become: true
  register: docker_keyfile
  stat:
    path: /etc/apt/keyrings/docker.gpg

- name: Download docker keyring file if it does not exist
  become: true
  when: not docker_keyfile.stat.exists
  shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: stat docker apt file so we can check if it exists
  become: true
  register: docker_apt_file
  stat:
     path: "/etc/apt/sources.list.d/docker.list"

- name: Add docker apt repository file if it does not exist
  when: not docker_apt_file.stat.exists
  become: true
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: install docker packages
  become: true
  package:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: create docker group, add users to this group to allow them to run docker without sudo
  become: true
  group:
    name: docker
    state: present

#- name: sudoless docker commands
#  become: true
#  user:
#    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
#    groups: docker
#    append: yes
