- name: assert required vars are set
  assert:
    that:
      - ssl_cert_folder != ""
      - ssl_cert_key != ""
      - ssl_cert != ""

- name: create folder for SSL certs
  file:
    path: "{{ ssl_cert_folder }}"
    state: directory
    owner: root
    group: root
    mode: "0770"

- name: create SSL keys if needed
  command: |
    openssl req -x509 -nodes -days 365 \
       -newkey rsa:4096 -keyout {{ ssl_cert_key }} -out {{ ssl_cert }} \
       -batch -subj '/CN=localhost' -sha256 -addext "subjectAltName = IP:127.0.0.1, IP:::1"

- name: ensure permissions on SSL cert files
  file:
    path: "{{ item }}"
    state: file
    owner: root
    group: root
    mode: "0770"
  with_items:
    - "{{ ssl_cert_key }}"
    - "{{ ssl_cert }}"
